/vehicle_params/wheelbase             : 2.79    # [m]           Longitudinal distance between front and rear axles
/vehicle_params/mass                  : 2300.0  # [kg]          Mass of the vehicle
/vehicle_params/inertia_z             : 4500.0  # [kg*m2]       Inertia of the vehicle around the vertical axis
/vehicle_params/front_axle_from_cog   : 1.24    # [m]           Longitudinal distance from the center of gravity to the front axle in the vehicle coordinate system
/vehicle_params/rear_axle_from_cog    : 1.55    # [m]           Longitudinal distance from the center of gravity to the rear axle in the vehicle coordinate system
/vehicle_params/steering_rack_ratio   : 14.7    # [1]           Steering rack ratio

// TODO: Fill params

/vehicle_params/vehicle_length        : 0.0     # [m]           Length of the vehicle
/vehicle_params/vehicle_width         : 0.0     # [m]           Width of the vehicle
/vehicle_params/vehicle_height        : 0.0     # [m]           Height of the vehicle
/vehicle_params/front_bumper          : 0.0     # [m]           Longitudinal distance to the front bumper in the vehicle coordinate system with origin at center of the rear axle
/vehicle_params/rear_bumper           : 0.0     # [m]           Longitudinal distance to the rear bumper in the vehicle coordinate system with origin at center of the rear axle
/vehicle_params/acc_long_sens_pos     : 0.0     # [m]           Longitudinal mounting position of the longitudinal acceleration sensor in vehicle coordinate system with origin middle of the rear axis
/vehicle_params/wheel_base            : 0.0     # [m]           Longitudinal distance between front and rear axles
/vehicle_params/wheel_track           : 0.0     # [m]           Distance between the centerline of two wheels on the same axle
/vehicle_params/v_characteristic      : 0.0     # [m/s]         Vehicle characteristic velocity: velocity at which the steering sensitivity of the vehicle is at maximum
/vehicle_params/grad_side_slip_ang    : 0.0     # [rad*s^2/m]   Ego Gradient Side Slip angle
/vehicle_params/wheel_circ_fl         : 0.0     # [m]           Front Left Wheel Circumference
/vehicle_params/wheel_circ_fr         : 0.0     # [m]           Front Right Wheel Circumference
/vehicle_params/wheel_circ_rl         : 0.0     # [m]           Rear Left Wheel Circumference
/vehicle_params/wheel_circ_rr         : 0.0     # [m]           Rear Right Wheel Circumference
/vehicle_params/front_whl_corn_stiff  : 0.0     # [N/rad]       Front wheel cornering stiffness
/vehicle_params/rear_whl_corn_stiff   : 0.0     # [N/rad]       Rear wheel cornering stiffness
