/vehicle_params/L:   2.79
/vehicle_params/m:   2300.0
/vehicle_params/jz:  4500.0
/vehicle_params/l1:  1.24
/vehicle_params/l2:  1.55
/vehicle_params/swr: 14.8
/vehicle_params/c1:  5000.0
/vehicle_params/c2:  5000.0
