/vehicle_params/wheelbase:            2.79   # m
/vehicle_params/mass:                 2300.0 # kg
/vehicle_params/inertia_z:            4500.0 # kg*m2
/vehicle_params/front_axle_from_cog:  1.24   # m
/vehicle_params/rear_axle_from_cog:   1.55   # m
/vehicle_params/steering_ratio:       14.8   
/vehicle_params/front_wheel_cornering_stiffness: 5000.0 # N/rad
/vehicle_params/rear_wheel_cornering_stiffness:  5000.0 # N/rad
