CtrlVehicleControlLatCompensatory:
  ros__parameters:
    /ctrl/ffGainOffsetGround:     1.0
    /ctrl/ffGainSlope:            0.0
    /ctrl/ffLookAheadTime:        0.68
    /ctrl/ffMinLookAheadDistance: 0.0
    /ctrl/steeringAngleLPFilter:  0.2
    /ctrl/fbLookAheadTime:        0.6
    /ctrl/fbPGain:                0.5
    /ctrl/fbDGain:                0.1
    /ctrl/fbIGain:                0.0
    /ctrl/fbThetaGain:            0.0
    /ctrl/fbMinLookAheadDistance: 0.0
    /ctrl/fbIntegralLimit:        3.0
    /ctrl/trajectory_distance:    50.0
    /ctrl/debugKPIs:              True