ctrl_vehicle_control_lat_compensatory:
  ros__parameters:
    /ctrl/compensatory/ffLookAheadTime:                    1.5
    /ctrl/compensatory/steeringAngleLPFilter:              0.6
    /ctrl/compensatory/fbLookAheadTime:                    0.6
    /ctrl/compensatory/fbPGain:                            1.25
    /ctrl/compensatory/fbDGain:                            0.05
    /ctrl/compensatory/fbIGain:                            0.05
    /ctrl/compensatory/fbIntegralLimit:                    0.5
    /ctrl/compensatory/trajectory_distance:                50.0
    /ctrl/compensatory/sigma_thetaFP:                      0.0
    /ctrl/compensatory/maxThetaFP:                         1.0
    /ctrl/compensatory/targetAccelerationFF_lpFilterCoeff: 0.5
    /ctrl/compensatory/targetAccelerationFB_lpFilterCoeff: 0.3
