float32	ax_ego_mps2
float32	ay_ego_mps2
float32	az_ego_mps2

float32	road_wheel_angle_front_rad
float32	steering_wheel_gradient
float32	torsion_bar_torque_nm

float32	vx_ego_mps

float32	yaw_rate_radps
float32	pitch_rate_radps
float32	roll_rate_radps

float32 global_position_x
float32 global_position_y
float32 global_position_z

float32 global_orientation_yaw
float32 global_orientation_pitch
float32 global_orientation_roll

uint8 gnss_status

int8 blinker

std_msgs/Header	zzz_header
uint32	zzz_sequence
float32	zzz_timestamp_s