std_msgs/Header header

std_msgs/Float32 target_speed

std_msgs/UInt8   curve_driving_style

std_msgs/UInt8   speed_up_acceleration_mode
std_msgs/UInt8   start_up_acceleration_mode
std_msgs/UInt8   straight_line_offset_mode
std_msgs/UInt8   lane_change_mode
std_msgs/UInt8   learnt_time_gap_level
std_msgs/UInt8   lateral_dynamic_mode
std_msgs/UInt8   yaw_rate_mode

std_msgs/UInt8   brake_jerk_mode
std_msgs/UInt8   acceleration_jerk_mode